version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    assignees:
      - ChristophShyper
    labels:
      - automatic

  # Enable version updates for Docker
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
    assignees:
      - ChristophShyper
    labels:
      - automatic
