name: GitHub Action for committing changes to a repository
author: Krzysztof Szyper / ChristophShyper / biotyk@mail.com
description: GitHub Action that will create a new commit and push it back to the repository
inputs:
  github_token:
    description: Personal Access Token for GitHub for pushing the code
    required: true
    default: ""
  add_timestamp:
    description: Whether to add timestamp to a new branch name
    required: false
    default: "false"
  amend:
    description: Whether to make amendment to the previous commit
    required: false
    default: "false"
  commit_prefix:
    description: Prefix added to commit message
    required: false
    default: ""
  commit_message:
    description: Commit message to set
    required: false
    default: ""
  force:
    description: Whether to force push
    required: false
    default: "false"
  force_without_lease:
    description: Whether to force push without lease (--force instead of --force-with-lease)
    required: false
    default: "false"
  no_edit:
    description: Whether to not edit commit message when using amend
    required: false
    default: "false"
  organization_domain:
    description: Name of GitHub Enterprise organization
    required: false
    default: github.com
  target_branch:
    description: Name of a new branch to push the code into
    required: false
    default: ""
outputs:
  files_changed:
    description: List of changed files
  branch_name:
    description: Name of the branch code was pushed into
runs:
  using: composite
  steps:
    - name: Run action
      run: ${{ github.action_path }}/run.sh
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_ADD_TIMESTAMP: ${{ inputs.add_timestamp }}
        INPUT_AMEND: ${{ inputs.amend }}
        INPUT_COMMIT_PREFIX: ${{ inputs.commit_prefix }}
        INPUT_COMMIT_MESSAGE: ${{ inputs.commit_message }}
        INPUT_FORCE: ${{ inputs.force }}
        INPUT_FORCE_WITHOUT_LEASE: ${{ inputs.force_without_lease }}
        INPUT_NO_EDIT: ${{ inputs.no_edit }}
        INPUT_ORGANIZATION_DOMAIN: ${{ inputs.organization_domain }}
        INPUT_TARGET_BRANCH: ${{ inputs.target_branch }}
branding:
  color: purple
  icon: upload-cloud
