name: Weekly build

on:
  schedule:
    # Run every week at 5.00 AM UTC
    - cron: "0 5 */7 * *"

jobs:
  build_and_push:
    name: Build & push
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v3.9.0
        with:
          install: true

      - name: QEMU
        uses: docker/setup-qemu-action@v3.4.0
        with:
          image: tonistiigi/binfmt:latest
          platforms: amd64,arm64

      - name: Build & push
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TERM: xterm-256color
        run: make push VERSION_PREFIX=test-
