name: Push to master

on:
  push:
    branches:
      - master

jobs:
  labels:
    name: Repo labels
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Labels' config
        shell: bash
        run: |
          mkdir -p .tmp
          curl -LsS https://raw.githubusercontent.com/devops-infra/.github/master/.github/labels.yml -o .tmp/labels.yml

      - name: Update labels
        uses: crazy-max/ghaction-github-labeler@v5.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .tmp/labels.yml

  lint:
    name: Linters
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

  build_test:
    name: Build test
    needs: lint
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1
        with:
          install: true

      - name: QEMU
        uses: docker/setup-qemu-action@v3.6.0
        with:
          image: tonistiigi/binfmt:latest
          platforms: amd64,arm64

      - name: Build test
        env:
          DOCKER_BUILDKIT: 1
          TERM: xterm-256color
        run: make build
